# Misc Scripts (Used if lcm buffer is too small)

alias lcmfix='$ROSIE_PROJ/scripts/lcm_fix'

# Rosie Scripts
alias build_rosie="$ROSIE_PROJ/scripts/build_rosie"
alias build_probcog="$ROSIE_PROJ/scripts/build_probcog"
alias build_agent="$ROSIE_PROJ/scripts/build_agent"
alias build_tools="$ROSIE_PROJ/scripts/build_rosie_tools"

alias run_probcog="$ROSIE_PROJ/scripts/run_probcog"
alias run_rosie="$ROSIE_PROJ/scripts/run_rosie"

source $ROSIE_PROJ/scripts/rosie_agents_completion.sh
source $ROSIE_PROJ/scripts/probcog_worlds_completion.sh

complete -F _probcog_worlds_completion run_probcog
complete -F _rosie_agents_completion run_rosie
complete -F _rosie_agents_completion build_agent

