#!/bin/bash

export PROBCOG_HOME=$ROSIE_PROJ/probcog
while [[ $# -gt 0 ]]
do
	key="$1"

	case $key in
		-t|--tabletop)
			export PROBCOG_HOME=$ROSIE_PROJ/tabletop
			;;
		-f|--fetch)
			export PROBCOG_HOME=$ROSIE_PROJ/fetch
			;;
		-m|--magicbot)
			export PROBCOG_HOME=$ROSIE_PROJ/probcog
			;;
		*)
			;;
	esac
	shift
done

cd $PROBCOG_HOME/java
ant
