#!/bin/bash

AGENT_NAME=""

# Run in background
BG="FALSE"

# Iterate over each argument given
while [[ $# -gt 0 ]]
do
	arg="$1"
	case $arg in
		-b|--background)
			BG="TRUE"
			;;
		*)
			AGENT_NAME="$1"
			;;
	esac
	shift
done

if [ "$AGENT_NAME" == "" ]; then 
	echo "Missing agent name"
	exit 1
fi

export CLASSPATH=$CLASSPATH:$PROBCOG_HOME/java/probcog.jar
echo $CLASSPATH

cd $ROSIE_HOME/test-agents/$AGENT_NAME/agent
if [ "$BG" == "TRUE" ]; then
	java -Djava.library.path=/Users/schatzju/Desktop/Soar/out edu.umich.rosie.gui.BasicRosieGUI rosie.$AGENT_NAME.config &
else
	java -Djava.library.path=/Users/schatzju/Desktop/Soar/out edu.umich.rosie.gui.BasicRosieGUI rosie.$AGENT_NAME.config
fi
