/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sphinxJNI */

#ifndef _Included_sphinxJNI
#define _Included_sphinxJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sphinxJNI
 * Method:    decodeAudio
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sphinxJNI_decodeAudio
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
