Deliver the package to Alice.
The goal is that Alice is holding the package.
Think of an office of Alice.
Deliver a water to Bob.

Go to the soar office.
Go to the april office.
Bring the package to the Alice.
The goal is that the Alice is holding the package.
Find the package.
Scan until you see the package.
Recall the Alice in a location.
Guide the Alice to the lab.
The goal is that the Alice is in the lab
Tell the Charlie a message
The goal is that the Charlie is heard the message
Ask "What is the message?"
"Hello Charlie, I'm rosie"
Remember the answer as the message
Explore until you see the Charlie
A storage location of a stapler is the copy room
Fetch a stapler
The goal is that the stapler is in the starting location
Remember the current location as the starting location
Find the stapler
Think of a storage location of the stapler
Go to the atrium
Fetch a paper
Unknown
Tell the Bob a message
"It's time for the meeting"
Guide the Bob to the atrium
Bring a water to the Bob

Fetch a package from the main office.
The goal is that the package is in the starting location.
Remember the current location as the starting location.
Go to the main office.
Pick up the package.
Go to the starting location.
Put down the package.
Fetch a stapler.
Explore until you see the stapler.

Fetch a soda
The goal is that the soda is in the starting location.
Remember the current location as the starting location.
Recall a soda in a location.
Go to the location.
Pick up the soda.
Go to the starting location.
Put down the soda.

Tell the Bob a message.
The goal is that the Bob is heard the message.
Ask "What is the message"
The message is "Aaron can meet between 3 and 5"
Remember the answer as the message.
Find the Bob.
Say the message to Bob.
