LCM = lcm-gen

LCMTYPES_NAMES := $(shell cd ../lcmtypes && ls *.lcm)

# Construct the pathnames to the java types.
LCMTYPES_JAVA := $(LCMTYPES_NAMES:%.lcm=%.java)
LCMTYPES_JAVA := $(addprefix src/edu/umich/rosie/lcmtypes/,$(LCMTYPES_JAVA))

SUFFIXES += .java .lcm

all: $(LCMTYPES_JAVA)


src/edu/umich/rosie/lcmtypes/%.java: ../lcmtypes/%.lcm
	$(LCM) -j  --jpath=src --jdefaultpkg=edu.umich.rosie.lcmtypes $<

clean:
	rm -rf *~ src/edu/umich/rosie/lcmtypes/*
