the name of the puzzle is jealous-husbands.
load init-husbands.
ok.
you can move the boat and a block on the current bank onto the opposite bank.
if an object is below a boat then it is current.
if a location is not below a boat then it is opposite.
you can move a block that is on the current bank and another block that is on the current bank and the boat onto the opposite bank.
load fail-husbands.
if a woman is on a bank and her husband is not on the bank then you lose.
if the last-name of a woman is the last-name of a man then the man is her husband.
ok.
load final-husbands.
the goal is that all the blocks are on a destination bank.
ok.
done.
load init-husbands2.
yes.
