the name of the puzzle is peg-solitaire.
load init-peg2.
ok.
if a peg is between an empty location and another peg then you can move the former peg onto a garbage plus move the latter peg onto the empty location. 
if an object is a block then it is a peg.
if a location is not below an object then it is empty.
load final-peg.
the goal is that the number of covered locations is one.
if a location is below an object then it is covered.
ok.
done.
load init-peg.
yes.
