/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package edu.umich.rosie.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class interaction_messages_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public String source;
    public int num_messages;
    public edu.umich.rosie.lcmtypes.interaction_message_t messages[];
 
    public interaction_messages_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x094ea4f9000e36cbL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(edu.umich.rosie.lcmtypes.interaction_messages_t.class))
            return 0L;
 
        classes.add(edu.umich.rosie.lcmtypes.interaction_messages_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + edu.umich.rosie.lcmtypes.interaction_message_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        __strbuf = new char[this.source.length()]; this.source.getChars(0, this.source.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.num_messages); 
 
        for (int a = 0; a < this.num_messages; a++) {
            this.messages[a]._encodeRecursive(outs); 
        }
 
    }
 
    public interaction_messages_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public interaction_messages_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static edu.umich.rosie.lcmtypes.interaction_messages_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        edu.umich.rosie.lcmtypes.interaction_messages_t o = new edu.umich.rosie.lcmtypes.interaction_messages_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.source = new String(__strbuf);
 
        this.num_messages = ins.readInt();
 
        this.messages = new edu.umich.rosie.lcmtypes.interaction_message_t[(int) num_messages];
        for (int a = 0; a < this.num_messages; a++) {
            this.messages[a] = edu.umich.rosie.lcmtypes.interaction_message_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public edu.umich.rosie.lcmtypes.interaction_messages_t copy()
    {
        edu.umich.rosie.lcmtypes.interaction_messages_t outobj = new edu.umich.rosie.lcmtypes.interaction_messages_t();
        outobj.utime = this.utime;
 
        outobj.source = this.source;
 
        outobj.num_messages = this.num_messages;
 
        outobj.messages = new edu.umich.rosie.lcmtypes.interaction_message_t[(int) num_messages];
        for (int a = 0; a < this.num_messages; a++) {
            outobj.messages[a] = this.messages[a].copy();
        }
 
        return outobj;
    }
 
}

