/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package edu.umich.rosie.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class interaction_message_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public String message;
    public String message_type;
 
    public interaction_message_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1e8e55019509f7e1L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(edu.umich.rosie.lcmtypes.interaction_message_t.class))
            return 0L;
 
        classes.add(edu.umich.rosie.lcmtypes.interaction_message_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        __strbuf = new char[this.message.length()]; this.message.getChars(0, this.message.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.message_type.length()]; this.message_type.getChars(0, this.message_type.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public interaction_message_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public interaction_message_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static edu.umich.rosie.lcmtypes.interaction_message_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        edu.umich.rosie.lcmtypes.interaction_message_t o = new edu.umich.rosie.lcmtypes.interaction_message_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.message = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.message_type = new String(__strbuf);
 
    }
 
    public edu.umich.rosie.lcmtypes.interaction_message_t copy()
    {
        edu.umich.rosie.lcmtypes.interaction_message_t outobj = new edu.umich.rosie.lcmtypes.interaction_message_t();
        outobj.utime = this.utime;
 
        outobj.message = this.message;
 
        outobj.message_type = this.message_type;
 
        return outobj;
    }
 
}

