The name of the puzzle is tower-of-hanoi-3.
load init-tower3.
ok.
you can move a clear block onto a clear object that is larger than the block.
if a location is not below an object then it is clear.
if the volume of a block is more than the volume of an object then the block is larger than the object.
load third-tower3.
the goal is that a location is reachable by a block.
if you can move a block onto an object then the object is reachable by the block.
ok.
done.
load third-tower3.
yes.