The name of the puzzle is tower-of-hanoi-3.
ok.
load final-tower3b.
The goal is that a medium block is below a small block and a large block is below the medium block and a blue location is below the large block.
if a block is on an object then the object is below the block.
ok.
load init-tower3.
you can move a clear block onto a clear object that is larger than the block.
if a location is not below an object then it is clear.
if the volume of a block is more than the volume of an object then the block is larger than the object.
done.
load init-tower3.
yes.
