the name of the puzzle is sokoban.
load init-sokoban.
ok.
if a location below a green block is adjacent to a clear location then you can move the block onto the clear location.
if a location is next to an object but it is not diagonal with the object then it is adjacent to the object.
if a location is not below an object then it is clear.
if a covered location is between a clear location and a current location then you can move a block on the covered location onto the clear location plus you can move a block on the current location onto the covered location.
if a location is below an object then it is covered.
if a location is below a green block then it is the current location.
load final-sokoban.
the goal is that a red block is on a red location and a blue block is on a blue location.
ok.
done.
load init-sokoban.
yes.
