load init-president.
The name of the game is president.
Ok.
If the value of a held card is the value of the bottom card then you can play the held card.
If a card is on a hand then it is held.
If a card is on a deck and it is not on another card then it is a bottom card.
If the value of a held card is two then you can play the card.
if a held card is higher than a bottom card then you can play the held card.
if the value of a card is more than the value of another card then the former card is higher than the latter card.
load final-president.
The goal is that a hand is clear.
If a block is not below an object then it is clear.
ok.
load fail-president.
If a dealer is clear then you lose.
ok.
done.
no.