The name of the puzzle is tower-of-hanoi-3.
load init-tower3.
ok.
you can move a clear block onto a clear object that is larger than the block.
if a location is not below an object then it is clear.
if the volume of a block is more than the volume of an object then the block is larger than the object.
load second-tower3.
if a block is reachable by an object then consider moving the object onto the block.
if you can move a block onto an object then the object is reachable by the block.
load final-tower3.
The goal is that there are two clear green locations.
ok.
done.
load init-tower3.
yes.