the name of the game is tic-tac-toe.
load init-tictactoe.
ok.
you can move a free clear red block onto a clear location.
if a block is not on a location then it is free.
if a location is not below an object then it is clear.
load final-tictactoe.
the goal is that three linear locations are captured.
if a location is below a red block then it is captured.
ok.
load fail-tictactoe.
if three linear locations are occupied then you lose.
if a location is below a blue block then it is occupied.
ok.
load third-tictactoe.
Prefer moving a block onto a fork location.
If the number of captured locations that are adjacent to a clear location is more than one then the location is a fork location.
if a location is next to an object but it is not diagonal with the object then it is adjacent to the object.
done.
no.
