the name of the puzzle is frogs-and-toads.
load init-frog.
ok.
you can move a frog that is on a location onto an available location that is to the right of the location.
if an object is a red block then it is a frog.
if a location is not below an object then it is available.
you can move a red block that is on a location onto an available location that is to the left of the location.
load second-frog.
if a location below a red block is to the right of a location below a blue block and the second location is to the right of an available location then you can move the red block onto the available location.
if a location below a blue block is to the left of a location below a red block and the second location is to the left of an available location then you can move the blue block onto the available location.
load final-frog.
the goal is that all the red blocks are on the red locations and all the blue blocks are on the blue locations.
ok.
done.
load init-frog.
yes.
