the name of the puzzle is peg-solitaire.
load init-peg2.
ok.
you can move a block jumpable by a covered location and a clear location onto a garbage and move a block on the covered location onto the clear location.
if a location below a block is between a clear location and a covered location then the block is jumpable by the covered location and the clear location.
if a location is not below an object then it is clear.
if a location is below an object then it is covered.
load final-peg.
the goal is that the number of covered locations is one.
ok.
done.
load init-peg.
yes.
