The name of the puzzle is tower-of-hanoi-3.
load init-tower3.
ok.
the name of an action is stack.
you can move a clear block onto a clear object that is larger than the block.
if a location is not below an object then it is clear.
if the volume of a block is more than the volume of an object then the block is larger than the object.
you can move a block that is movable to a location onto the location.
if you can stack a block onto an object then the block is movable to the object.
load second-tower3.
you can move a block that is movable to a clear block onto the clear block.
avoid moving a block that was previously moved.
load final-tower3.
The goal is that there are two clear green locations.
ok.
done.
load init-tower3.
yes.