the name of the puzzle is simple-maze.
load init-maze.
ok.
if a blue block is on a location then you can move the block onto a neighbor of the location.
if a location is adjacent to an object then the object is a neighbor of the location.
if a location is next to an object but it is not diagonal with the object then it is adjacent to the object.
load final-maze.
the goal is that a blue block is on a blue location.
ok.
done.
load init-maze.
yes.
