the name of the game is tic-tac-toe.
load init-3mens.
ok.
you can move a free clear red block onto a clear location.
if a block is not on a location then it is free.
if a location is not below an object then it is clear.
Prefer moving a block onto a corner location over moving the block onto an edge location.
If the number of locations diagonal with another location is one then the location is a corner location.
If the number of locations diagonal with another location is two then the location is a edge location.
your opponent can move a free clear blue block onto a clear location.
load final-3mens.
the goal is that three linear locations are captured.
if a location is below a red block then it is captured.
ok.
load fail-3mens.
if three linear locations are occupied then you lose.
if a location is below a blue block then it is occupied.
ok.
done.
load init-3mens.
yes.
go.
