the name of the puzzle is eight-puzzle00.
load init-8puzzle.
ok.
the name of the action is slide-block22.
if a block is on a location that is adjacent to a clear location then you can move the block onto the clear location.
if a location is next to an object but it is not diagonal with the object then it is adjacent to the object.
if a location is not below an object then it is clear.
load final-8puzzle.
the goal is that there are eight matched locations.
if the color of a location is the color of the block that is on the location then the location is matched.
ok.
done.
no.
the name of the puzzle is five-puzzle22.
load init-5puzzle.
ok.
the name of the action is slide-block22.
load final-5puzzle.
the goal is that there are five matched locations.
ok.
done.
no.
the name of the puzzle is mahjong44.
load init-mahjong.
ok.
if the color of a clear free block is the color of another clear free block then you can move the blocks onto a garbage.
if a block is not on a location then it is free.
load final-mahjong.
the goal is that all blocks are on a garbage.
ok.
done.
no.
The name of the puzzle is tower-of-hanoi-366.
load init-tower3.
ok.
the name of an action is stack-block22.
you can move a clear block onto a clear object that is larger than the block.
if the volume of a block is more than the volume of an object then the block is larger than the object.
load final-tower3.
The goal is that a small block is on a medium block and the medium block is on a large block and the large block is on a blue lo
cation.
ok.
done.
no.
the name of the game is risk88.
load init-risk.
ok.
if the number of the blocks on a captured location is more than one then you can attack an occupied location that is next to the
 captured location.
if a location is below a red block then it is captured.
if a location is below a blue block then it is occupied.
load final-risk.
the goal is that all locations are captured.
ok.
load fail-risk.
if all locations are occupied then you lose.
ok.
done.
no.