the name of the game is risk.
load init-risk.
ok.
if the number of the blocks on a captured location is more than one then you can attack an occupied location that is next to the captured location.
if a location is below a red block then it is captured.
if a location is below a blue block then it is occupied.
Prefer attacking an occupied location.
load final-risk.
the goal is that all locations are captured.
ok.
load fail-risk.
if all locations are occupied then you lose.
ok.
done.
no.
