python buildnewscript.py
sh buildrun2.sh
python buildnewscript.py
sh buildrun2.sh
python buildnewscript.py
sh buildrun2.sh
python buildnewscript.py
sh buildrun2.sh
python buildnewscript.py
sh buildrun2.sh
