the name of the game is tic-tac-toe.
load init-tictactoe.
ok.
you can move a free piece that is yours onto a clear location.
an object that is not on a location is free.
if an object is a block then it is a piece.
if a piece is red then it is yours.
a location that is not below an object is clear.
the opponent can move a free piece that is theirs onto a clear location.
if a piece is blue then it is theirs.
the name of the goal is three-in-a-row.
load final-tictactoe.
ok.
the goal is that three linear locations are captured.
a location that is below a red piece is captured.
the name of the failure is opp-in-a-row.
load fail-tictactoe.
ok.
if three linear locations are occupied then you lose.
a location that is below a blue piece is occupied.
done.
no.
load init-xotictactoe.
the name of the game is xo-tac-toe.
ok.
you can write one onto a clear location.
if the value of a location is absent then the location is clear.
the opponent can write two onto a clear location.
load final-xotictactoe.
the name of the goal is three-in-a-row.
if the value of a location is one then the location is captured.
load fail-xotictactoe.
the name of the failure is opp-in-a-row.
if the value of a location is two then the location is occupied.
done.
no.