The name of the game is eight-puzzle
If a block is on a location that is adjacent to a clear location then you can move the block onto the clear location.
if a block is not below an object then it is clear
If a location is next to a clear location but it is not diagonal with the clear location then it is adjacent to the clear location.
The goal is that eight locations are matched.
If the color of a location is the color of the block that is on the location then the location is matched.
Done.
The name of the game is tower-of-hanoi.
You can move a clear block onto a clear object that is larger than the block.
The goal is that a small block is on a medium block and the medium block is on a large block and the large block is on a blue location