Deliver the package to the soar office.
The goal is that the package is in the soar office.
Ok.
Face north.
Follow the right wall until you see a second intersection.
Turn right.
Follow the right wall until you see a door.
You are in the soar office.
Fetch a stapler from the copy room.
The goal is that the stapler is in the starting location.
Remember the current location as the starting location.
Deliver the stapler to the main office.
