The name of the game is eight-puzzle
The name of an action is slide-block.
If a block is on a location that is adjacent to a clear location then you can move the block onto the clear location.
if a block is not below an object then it is clear
If a location is next to a clear location but it is not diagonal with the clear location then it is adjacent to the clear location.
the name of the goal is all-matched
The goal is that eight locations are matched.
If the color of a location is the color of the block that is on the location then the location is matched.
Done.