The name of the game is othello-game.
The name of an action is capture-block.
If a piece is red then it is an enemy piece.
If a location is below an enemy piece then the location is occupied.
If the locations between a clear location and a captured location are occupied then you can place a piece on the clear location.
If the locations between a clear location and a captured location are below red blocks then you can place a free block on the clear location.
if a block is not below an object then it is clear
The name of the goal is covered-win.
The goal is that all locations are covered and the number of captured locations is more than the number of occupied locations.
Done.