The name of the puzzle is tower-of-hanoi.
Ok.
You can move a clear block onto a clear object that is larger than the block.
if a block is not below an object then it is clear.
The goal is that a small block is on a medium block and the medium block is on a large block and the large block is on a blue location.
Ok.
Done.
Yes.
The name of the goal is all-stacked.
The name of an action is stack-block.