the name of the game is three-mens-morris
init-3mens
ok
you can move an available block onto a location
if a block is red and the block is free then it is available
if a block is not on a location then it is free
the name of an action is place-block
if a location is not below an object then it is clear
if a block is not on a location then it is free
if a block is free then it is available
if a block is red then it is crimson
you can move a free crimson block onto a clear location
ok
done