the name of the puzzle is simple-maze.
init-maze.
ok.
if a red block is on a location that is adjacent to a clear location then you can move the block onto the clear location.
if a location is not below an object then it is clear.
if a location is next to a clear location but it is not diagonal with the clear location then it is adjacent to the clear location.
final-maze.
the goal is that a red block is on a red location.
ok.
done.
init-maze.
yes.
