The name of the puzzle is tower-of-hanoi-3.
init-tower3.
ok.
you can move a clear block onto a clear object.
if a location is not below an object then it is clear.
fail-tower3.
if a block is below an object that is larger than the block then you lose.
ok.
final-tower3.
The goal is that a small block is on a medium block and the medium block is on a large block and the large block is on a blue location.
ok.
done.
init-tower3.
yes.
