the name of the puzzle is missionaries-and-cannibals.
init-mac.
ok.
you can move a block on the current bank onto a clear boat.
if an object is below a boat then it is current.
if a location is not below an object then it is clear.
third-mac.
you can move a boat and the blocks on the boat onto the opposite bank.
if a location is not below a boat then it is opposite.
you can move a block on the boat onto the current bank.
second-mac.
if there is one block on a boat then you can move a block on the current bank onto the boat.
fail-mac.
if the number of cannibals on the opposite bank is more than the number of missionaries on the bank then you lose.
ok.
final-mac.
the goal is that all the cannibals are on a red bank and all the missionaries are on the bank.
ok.
done.
init-mac.
yes.
