package edu.umich.rosie.tools.config;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Map;

public class SmemConfigurator {
	
	public static ArrayList<String> configureSmem(File inputFile, File smemDir, File outputDir, String agentName){
		ArrayList<String> filesWritten = new ArrayList<String>();
		try{
			String actionsFilename = outputDir + "/smem_actions_" + agentName + ".soar";
			Writer actionsFile = new BufferedWriter(new OutputStreamWriter(
					new FileOutputStream(actionsFilename), "utf-8"));
			actionsFile.write("# Placeholder for autogenerated actions smem file");
			actionsFile.close();
			filesWritten.add(actionsFilename);

			String relationsFilename = outputDir + "/smem_relations_" + agentName + ".soar";
			Writer relationsFile = new BufferedWriter(new OutputStreamWriter(
					new FileOutputStream(relationsFilename), "utf-8"));
			relationsFile.write("# Placeholder for autogenerated relations smem file");
			relationsFile.close();
			filesWritten.add(relationsFilename);

			String propertiesFilename = outputDir + "/smem_properties_" + agentName + ".soar";
			Writer propertiesFile = new BufferedWriter(new OutputStreamWriter(
					new FileOutputStream(propertiesFilename), "utf-8"));
			propertiesFile.write("# Placeholder for autogenerated properties smem file");
			propertiesFile.close();
			filesWritten.add(propertiesFilename);
			
		} catch (Exception e){
			e.printStackTrace();
		}	
		return filesWritten;
	}

    public static void main(String[] args) {
    	if (args.length < 2){
    		System.err.println("SmemConfigurator requires 2 argument:\n" + 
    							"  1: The input filename with the smem configuration information\n" + 
    							"  2: The name to use when creating files (e.g. smem_actions_<name>.soar\n" + 
    							"  3 [OPT]: The directory containing the semantic memory source files\n" + 
    							"           Defaults to $ROSIE_HOME/agent/init-smem");
    		System.exit(1);
    	}
    	
    	File inputFile = new File(args[0]);
    	String agentName = args[1];
    	
    	File smemDir = null;
    	if (args.length >= 3){
    		smemDir = new File(args[2]);
    	} else {
    		String rosieHome = System.getenv("ROSIE_HOME");
    		if (rosieHome == null){
    			System.err.println("$ROSIE_HOME environment variable is not set");
    			System.exit(1);
    		}
    		smemDir = new File(rosieHome + "/agent/init-smem");
    	}
    	
    	File outputDir = new File(System.getProperty("user.dir"));
    	
    	SmemConfigurator.configureSmem(inputFile, smemDir, outputDir, agentName);
    }

}
